### ISSUE TITLE
Send the Code

### ISSUE THREAD

**Issue by artem-konovalov-personal** [nesterone/sf-eng-init-gl-spring-2016#113]
Exercise [Send Your Code](https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/06-our-model-of-collaboration/our-model-of-collaboration.md#exercise-send-your-code)

**Comment by nervebassmaster** [comment]
Closed [#113](https://github.com/nesterone/sf-eng-init-gl-spring-2016/issues/113)
