### ISSUE TITLE
Contribute to Course content

### ISSUE THREAD

**Issue by DeuceX** [nesterone/sf-eng-init-gl-spring-2016#138]
[Contribute to Course content](https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/06-our-model-of-collaboration/our-model-of-collaboration.md#exercise-contribute-to-course-content)

**Comment by nesterone** [comment]
There are conflicts during merge, waiting for resolving conflicts on contributor's side
