### ISSUE TITLE
Provide more test cases for exercises

### ISSUE THREAD

**Issue by nesterone** [nesterone/sf-eng-init-gl-spring-2016#408]

**Comment by nesterone** [comment]
Provide more test cases in syntax section for exercieses skeletons

**Comment by artem-konovalov-personal** [comment]
I have added few additional check cases to the course exercises. This committed changes have been automatically added to the [previous commit](https://github.com/nesterone/sf-eng-init-gl-spring-2016/pull/453) to the master-branch

**Comment by nesterone** [comment]
Could I ask you to assign pull request to that issue ?

**Comment by artem-konovalov-personal** [comment]
Closed [#408](Closed[#408]%28https://github.com/nesterone/sf-eng-init-gl-spring-2016/issues/408%29)

**Comment by nervebassmaster** [comment]
Closed [#408](Closed[#408](https://github.com/nesterone/sf-eng-init-gl-spring-2016/issues/408))

**Comment by artem-konovalov-personal** [comment]
Alas, I can't assign pull request to this issue correctly. When I add `Closed #408` to the description into this issue or write this command into the description in the [453 issue](https://github.com/nesterone/sf-eng-init-gl-spring-2016/issues/453), it hides [this one](https://github.com/nesterone/sf-eng-init-gl-spring-2016/issues/408) from waffle. But when I return all changes back - it assigns the pull to this (408) issue, but after an hour or even less this pull request becomes hidden again
