### ISSUE TITLE
Update Exercises and test pre-commit hook

### ISSUE THREAD

**Issue by nesterone** [nesterone/sf-eng-init-gl-spring-2016#409]
https://github.com/nervebassmaster/sf-eng-init-gl-spring-2016/pull/4

**Comment by artem-konovalov-personal** [comment]
- I have merged the pull request from `nesterone:nervebassmaster` to `nervebassmaster:exercises` branch;
- I have run `npm install` and after this operation I haven't had any errors; 
- I have run `npm run lint` and then I also haven't had any errors;
- I have made changes in `isEven.js` file for an exercise and after `git status` I see the correct result with one changed and uncommitted file;
  ![alt text](http://storage2.static.itmages.com/i/16/0411/h_1460386466_2605743_ed25e1766f.png);
- Then I have run `npm run lint` to check this file for any errors. I hadn't any errors and I have added changed file to commit and then I have committed these changes;
- I have got finished commit and got this message in console:
  ![alt text](http://storage2.static.itmages.com/i/16/0411/h_1460386788_2062312_e479618fe1.png)
- Then I have successfully pushed this commit into _remote branch_ on github;
  ![alt text](http://storage1.static.itmages.com/i/16/0411/h_1460386969_2297790_28e38edcdd.png)

**Then I have done one mistake advisedly,  got an error from EsLint  but I have finished this commit successfully even with this EsLint's error**

**Comment by artem-konovalov-personal** [comment]
I guess, I know how I can resolve this ugly behavior. I have `pulled` the remote `exercise` branch to the local `exercise` branch again, have run `npm install` again and now it works correctly.

**Comment by artem-konovalov-personal** [comment]
- I have created a `test` branch for testing `pre-commit hook` and I have changed some file in this branch from the empty file to the file which contains some bullshit instead the correct code. We can see a couple of errors from CodeInspector:
  ![alt text](http://storage8.static.itmages.com/i/16/0414/h_1460624619_3470719_20784b0c92.png)
- I have **saved** these ugly **changes** and you can see the proof of this in the following screenshot:
  ![alt text](http://storage1.static.itmages.com/i/16/0414/h_1460624666_8845627_9a268341a2.png)
- I have **indexed** this changed **file** successfully:
  ![alt text](http://storage4.static.itmages.com/i/16/0414/h_1460624818_2831988_11a64f41b1.png)
- But if I wanna **commit** these wrong ugly changes I get a message, which tell me that **I couldn't make the commit with wrong statements**:
  ![alt text](http://storage6.static.itmages.com/i/16/0414/h_1460625149_5562092_6bab0cd592.png)
  To conclude, I have changed this file correctly and `ESLinter` doesn't have any proofs that I'm not right:
  ![alt text](http://storage1.static.itmages.com/i/16/0414/h_1460625554_9328187_ece2a9252a.png)
  ![alt text](http://storage8.static.itmages.com/i/16/0414/h_1460625636_4120058_4b10ad90da.png)
  I can index this file and make commit successfully:
  ![alt text](http://storage6.static.itmages.com/i/16/0414/h_1460625773_8377024_b45b874819.png)

**Comment by artem-konovalov-personal** [comment]
**But!**
If I wanna run the console linter to check my file for errors, I get the following output:
![alt text](http://storage3.static.itmages.com/i/16/0414/h_1460627848_7779647_5e537becb5.png)
I mean, linter shows to me errors in the file, but as an additional present I get that message about some errors.
- I have checked my node's and npm's version (they are 5.10.1 and 3.8.6). You can see them on the previous screenshot;
- For example, I can use `npm run lint --force` to avoid these error messages;
- I have added `|| true` code into the `package.json` file, but, actually, this was not a very good idea, because when I use this additional code I can avoid the pre-commit block and commit changes with a lot of mistakes;
  ![alt text](http://storage6.static.itmages.com/i/16/0414/h_1460647055_4604064_3b1204ab55.png)

**Comment by nesterone** [comment]
As far as I see 'true' would prevent git hook to fail, because it won't send error code, so let's go with errors from npm but more strict hooks rules

**Comment by nesterone** [comment]
As think we can extend pre-hooks for other team members, thanks for testing that approach.
