### ISSUE TITLE
Overview of 5 most poplar browser

### ISSUE THREAD

**Issue by artem-konovalov-personal** [nesterone/sf-eng-init-gl-spring-2016#583]
Overview of 5 most popular browser

**Comment by artem-konovalov-personal** [comment]
!["alt text"](https://www.uptime.nl/wp-content/uploads/browser-wars.jpg)

**Overview of 5 most popular browsers:**

| Features | Google Chrome | Mozilla Firefox | Opera | Safari | Internet Explorer |
| --- | --- | --- | --- | --- | --- |
| **Engine** | [Blink](https://en.wikipedia.org/wiki/Blink_%28web_engine%29) | [Gecko](https://en.wikipedia.org/wiki/Gecko_%28software%29) | [Blink](https://en.wikipedia.org/wiki/Blink_%28web_engine%29) (Since Opera 15.0) | [Webkit](https://en.wikipedia.org/wiki/WebKit) | [Trident](https://en.wikipedia.org/wiki/Trident_%28layout_engine%29) |
| **Licence** | GNU LGPL, BSD-style | MPL | GNU LGPL, BSD-style | GNU LGPL, BSD-style | Proprietary |
| **Programming language** | C++ | C++ | C++ | C++ | C++ |
| **First release** | 3 April 2013 | 7 December 1998 | 3 April 2013 | 7 January 2003 | April 1997 |
| **Cost** | Free | Free | Free | Included with OS X | Included with Windows |
| **OS Support** | Windows, OS X, Linux, Android, iOS | Windows, OS X, Linux, BSD, Android, iOS, Other Unix | Windows, OS X, Linux, BSD, Android, iOS, Other Unix | Windows, OS X,  iOS | Windows, OS X, Other Unix |

![alt text](https://joveeno.files.wordpress.com/2010/04/pageload.png)
![alt text](https://www.dailytut.com/wp-content/uploads/2010/06/browser-performance-3.jpg)
![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Usage_share_of_web_browsers_%28Source_StatCounter%29.svg/600px-Usage_share_of_web_browsers_%28Source_StatCounter%29.svg.png)

**SUMMARY**
- Thus we can see that all of examined browsers are written on C++ language;
- All of them use different web-engines, except both Google Chrome and Opera use Blink web-engine.;
- All of those browsers are free of charge but Safari and Internet Explorer delivered right into the operation system;
- All of them are supported by different operation systems.
- The fastest browser for time of page downloading is Opera. The slowest is Google Chrome;
- The fastest browser for time of page downloading is Opera. The slowest is Internet Explorer;
- And what about browsers usage - Internet Explorer was the most popular browser at 2009 and now the most popular browser is Google Chrome.
- The slowest browser for DOM selection speed is Enternet Explorer and also it is the almost slowest one for the page download speed. 

![alt text](http://substack.net/images/browsers/war_of_the_browsers.png)

**Comment by nesterone** [comment]
Perfect !
