### ISSUE TITLE
Examples of Overengineering

### ISSUE THREAD

**Issue by DeuceX** [nesterone/sf-eng-init-gl-spring-2016#62]
https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/03-few-simple-principles/few-simple-principles.md#exercise-2

**Comment by DeuceX** [comment]
## Overengineering

**Overengineering** is the designing of a product to be more robust or complicated than is necessary for its application, either (charitably) to ensure sufficient factor of safety, sufficient functionality, or because of design errors. 
1. 40 Watt Light bulb lamp that is able to work in 30 kVolt system.
   !["lamp"](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSRBs3Ey6X0WLcfM0WiXtJsFpZGTaE96Y8KNC81IrSjRIbwefF_CA)
2. Titanium spoon
3. Small boat for 3 people (without luggage space), but with load capacity of 5000 kg
4. A cup made of bulletproof glass
5. And the last one is the real example of over-engineering:

!["nokia"](http://i2.kym-cdn.com/entries/icons/original/000/008/134/nokia-3310-troubleshooting.jpg)

**Comment by nesterone** [comment]
#3 under question
