### ISSUE TITLE
5 examples of overengineering

### ISSUE THREAD

**Issue by artem-konovalov-personal** [nesterone/sf-eng-init-gl-spring-2016#63]
[Exersice](https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/03-few-simple-principles/few-simple-principles.md#exercise-2) about providing 5 imaginary or real examples of Overengineering

**Comment by artem-konovalov-personal** [comment]
# 5 REAL EXAMPLES OF _[OVERENGINEERING](https://en.wikipedia.org/wiki/Overengineering)_

| **Example** | **Image** |
| --- | :-: |
| Phone function tablet | ![alt text](http://allplanshets.ru/wp-content/uploads/2015/02/planshetophon.jpg) |

---

|  |  |
| --- | :-: |
| Strange guitar | ![alt text](http://www.porjati.ru/uploads/posts/2011-02/1298397562_a8.jpg) |

---

|  |  |
| --- | :-: |
| Motorcycle-limousine | ![alt text](http://stat17.privet.ru/lr/0916fb0784649371fded6dfc25fc1351) |

---

|  |  |
| --- | :-: |
| Unholy baby carriage | ![alt text](http://proxy11.media.online.ua/uol/r3-bd2865c449/4e822c167f1bb.jpg) |

---

|  |  |
| --- | :-: |
| Women's shoes | ![alt text](http://www.rulez-t.info/uploads/posts/2009-02/1235079645_xren_06.jpg) |

**Comment by nesterone** [comment]
1 and 2 are good, but others not approved

**Comment by artem-konovalov-personal** [comment]
Just for fun:
- [Useful thing](http://debri.ru/uploads/posts/2011-02/1296541808_02.jpg);
- [Unuseful thing](http://www.rosspen.com/uploads/posts/55214768-neobychnye-predmety-interera.jpg);
- [Painful thing](http://omebli.ua/uploads/tinyimages/sofa04.jpg)
