### ISSUE TITLE
Discover Developer Tools

### ISSUE THREAD

**Issue by DeuceX** [nesterone/sf-eng-init-gl-spring-2016#78]
- Chapter 1: Getting Started & Basic DOM and Styles
- Chapter 2: Advanced DOM and Styles
- Chapter 3: Working With the Console
- Chapter 4: Debugging JavaScript
- Chapter 5: Network
- Chapter 6: Profiles
- Chapter 7: Memory

**Comment by nesterone** [comment]
I have an update, so
you have to go through additional Chapters 

https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/03-few-simple-principles/few-simple-principles.md#workshop-discover-developer-tools
