### ISSUE TITLE
Creating and Modifying a Repository

### ISSUE THREAD

**Issue by DeuceX** [nesterone/sf-eng-init-gl-spring-2016#84]
[Lesson 2: Creating and Modifying a Repository](https://www.udacity.com/course/viewer#!/c-ud775/l-2969618657/m-2960548760)

**Comment by DeuceX** [comment]
#### Links to my repository with asteroids:
- _Asteroids v2.0_: https://github.com/DeuceX/asteroids2

---

**What happens when you initialize a repository? Why do you need to do it?**

When you initialize a repository, you give a command for git to trace all the changes in the repository. You need it, because until you give this command, your changes won't be saved in git.

---

**How is the staging area different from the working directory and the repository? What value do you think it offers?**

Working directory: It's your working directory, where you can make changes, prepare files for commits, add or delete files etc
Staging Area: It's a place where you add files that you think are good for current commit not to commit all the changes
Repository: It's a place where all the newest version of files exist and where all the history is saved
![img](https://git-scm.com/book/en/v2/book/01-introduction/images/areas.png)

So, as we see, staging area is different because it has only files that you want to add for commit. It's usefull not to add files that you dont want to commit

---

**How can you use the staging area to make sure you have one commit per logical change?**

You can add to staging area only that files, that are relied to one logical change

---

**What are some situations when branches would be helpful in keeping your history organized? How would branches help?**

It's useful when you decide to make a new version of a program or to add some new functionality, but there is a chance that you will need an older version later. Thereby, not to checkout all the latest version to find the one that you need, you can just switch a branch and enjoy the functionality you needed.

---

**How do the diagrams help you visualize the branch structure?**

When you see the full picture that shows the branch structury it's much easier and takes less time to understand it.
![img](https://www.atlassian.com/pt/git/workflows/pageSections/00/contentFullWidth/0/tabs/02/pageSections/09/contentFullWidth/0/content_files/file0/document/git-workflow-release-cycle-3release.png)

---

**What is the result of merging two branches together? Why do we represent it in the diagram the way we do?**

The result of merging two braches together is one branch, that consists of files from branch A and branch B.
As I answered earlier, diagrams help people to see the full picture, it's very easy and 

---

**What are the pros and cons of Git’s automatic merging vs. always doing merges manually?**

Pros: It's much faster if you this automatically and computer will not miss anything.
Cons: If you do merging manually - you can make a descission if you need some files/code or not for each file. So you will not break the program.

**Comment by nesterone** [comment]
good with images ;-)
