### ISSUE TITLE
Build a Pomodoro Clock Incomplete

### ISSUE THREAD

**Issue by bazzika** [nesterone/sf-eng-init-gl-spring-2016#843]

**Comment by yzhbankov** [comment]
![i23 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/13466225/23206584/df2e7bb2-f8f6-11e6-8b3b-b2173c5ba100.jpg)

**Comment by yzhbankov** [comment]
![i24 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/13466225/23206600/e7a0449c-f8f6-11e6-8898-79a0c7b57512.jpg)
![i25 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/13466225/23206607/ec149140-f8f6-11e6-9843-41f56a80d60e.jpg)
