### ISSUE TITLE
Learn Git Branching

### ISSUE THREAD

**Issue by DeuceX** [nesterone/sf-eng-init-gl-spring-2016#86]
[Learn Git Branching](http://pcottle.github.io/learnGitBranching)

**Comment by nesterone** [comment]
Please, profs with screenshots

**Comment by DeuceX** [comment]
![img](http://content.screencast.com/users/BragaDmitriy/folders/Jing/media/d06bf81e-9b23-403a-b517-a27effc6d6af/2016-03-26_1135.png)

![img](http://content.screencast.com/users/BragaDmitriy/folders/Jing/media/d10e423b-ade8-4875-8d4d-2434754cd161/2016-03-26_1253.png)
