### ISSUE TITLE
Navigating a Commit History

### ISSUE THREAD

**Issue by bazzika** [nesterone/sf-eng-init-gl-spring-2016#91]
https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/05-git-and-github/git-and-github.md#workshop-commit-history

**Comment by bazzika** [comment]
How did viewing a diff between two versions of a file help you see the bug that
was introduced?

    Fill in your answer here

How could having easy access to the entire history of a file make you a more
efficient programmer in the long term?

    Fill in your answer here

What do you think are the pros and cons of manually choosing when to create a
commit, like you do in Git, vs having versions automatically saved, like Google
docs does?

    Fill in your answer here

Why do you think some version control systems, like Git, allow saving multiple
files in one commit, while others, like Google Docs, treat each file separately?

    Fill in your answer here

How can you use the commands git log and git diff to view the history of files?

    Fill in your answer here

How might using version control make you more confident to make changes that
could break something?

    Fill in your answer here

Now that you have your workspace set up, what do you want to try using Git for?

    Fill in your answer here

**Comment by bazzika** [comment]
https://github.com/bazzika/pappu-pakia/commit/03541e253c504a6234c377909bdcd9e94a338d79

**Comment by nesterone** [comment]
reflections ....

**Comment by bazzika** [comment]
**How did viewing a diff between two versions of a file help you see the bug that
was introduced?**
It gives us posibillity find of what you have changed by line program. It shows with "-" symbols which were removed from document and with "+" - symbols which were added

**How could having easy access to the entire history of a file make you a more
efficient programmer in the long term?**
You have posibillity to check and find all your changes and return to necessary version of your program.

**What do you think are the pros and cons of manually choosing when to create a
commit, like you do in Git, vs having versions automatically saved, like Google
docs does?**
Automatically conservation is not good if you have done a lot of changes for others parts of code. When you create a commit you define functional part of code.

**Why do you think some version control systems, like Git, allow saving multiple
files in one commit, while others, like Google Docs, treat each file separately?**
Git has functional approach. It means you create commit about some functional feature/changes of part of code. It can include a few files or part of file.

**How can you use the commands git log and git diff to view the history of files?**
git log lists the commits made in that repository in reverse chronological order – that is, the most recent commits show up first.git-diff - show changes between commits.

**How might using version control make you more confident to make changes that
could break something?**
Git allows you rollback to correct version of program with checkout to commit before commit where error had appeared. 

**Now that you have your workspace set up, what do you want to try using Git for?**
I'll try to view list of commits of repository and look for changes.
