### ISSUE TITLE
Creating and Modifying a Repository

### ISSUE THREAD

**Issue by bazzika** [nesterone/sf-eng-init-gl-spring-2016#92]
https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/05-git-and-github/git-and-github.md#workshop-creating-and-modifying-a-repository

**Comment by bazzika** [comment]
What happens when you initialize a repository? Why do you need to do it?

How is the staging area different from the working directory and the repository?
What value do you think it offers?

How can you use the staging area to make sure you have one commit per logical
change?

What are some situations when branches would be helpful in keeping your history
organized? How would branches help?

How do the diagrams help you visualize the branch structure?

What is the result of merging two branches together? Why do we represent it in
the diagram the way we do?

What are the pros and cons of Gitâ€™s automatic merging vs. always doing merges
manually?

**Comment by bazzika** [comment]
https://github.com/bazzika/asteroids

**Comment by nesterone** [comment]
reflections ...

**Comment by bazzika** [comment]
**What happens when you initialize a repository? Why do you need to do it?**
The git init command creates a new Git repository. It can be used to convert an existing, unversioned project to a Git repository or initialize a new empty repository. Executing git init creates a .git subdirectory in the project root, which contains all of the necessary metadata for the repo. Aside from the .git directory, an existing project remains unaltered .

**How is the staging area different from the working directory and the repository?**
**What value do you think it offers?**
The working directory is a single checkout of one version of the project. These files are pulled out of the compressed database in the Git directory and placed on disk for you to use or modify.
The repository (Git directory) is where Git stores the metadata and object database for your project. This is the most important part of Git, and it is what is copied when you clone a repository from another computer.
Unlike the other systems, Git has something called the "staging area" or "index". This is an intermediate area where commits can be formatted and reviewed before completing the commit.This allows you to stage only portions of a modified file.

**How can you use the staging area to make sure you have one commit per logical
change?**
You be able to add in the staging area a few files which including functional change. Before that you may check list of files with command 'git status'.

**What are some situations when branches would be helpful in keeping your history
organized? How would branches help?**
The main core of branch is a unique series of code changes with a unique name. Each repository can have one or more branches. Particulary for each functional change. It helps us define parts of code.

**How do the diagrams help you visualize the branch structure?**
it helps you easier understand you how realize next step.

**What is the result of merging two branches together? Why do we represent it in
the diagram the way we do?**
Merging two branches creates one new branch which includes all commits of first and second branches.

**What are the pros and cons of Git's automatic merging vs. always doing merges
manually?**
Automatic merging is safety to add all changes and files, but may appear some conflict. These conflict you can manage manually.
