### ISSUE TITLE
Github's Adventure Game

### ISSUE THREAD

**Issue by bazzika** [nesterone/sf-eng-init-gl-spring-2016#93]
https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/05-git-and-github/git-and-github.md#workshop-githubs-adventure-game

**Comment by bazzika** [comment]
https://github.com/udacity/create-your-own-adventure/pull/4022/commits/a579c48a3dbc5297b018b6ce18bb79dc479d2369

**Comment by nesterone** [comment]
reflections ...

**Comment by bazzika** [comment]
**When would you want to use a remote repository rather than keeping all your work
local?**
I'll remote repository if i'm going to work from another computer or collaborate with ohter people.

**Why might you want to always pull changes manually rather than having Git
automatically stay up-to-date with your remote repository?**
Some bugs can appear with automatically updating.

**Describe the differences between forks, clones, and branches.  When would you
use one instead of another?**
_A clone_ is simply a copy of a repository.
_A branch_ is something that is within a repository. Conceptually, it represents a thread of development. You usually have a master branch, but you may also have a branch where you are working on some feature xyz, and another one to fix bug abc. When you have checked out a branch, any commits you make will stay on that branch and not be shared with other branches until you merge them with or rebase them onto the branch in question.
_A fork_ is another way of saying clone or copy. So, unlike a branch, a fork is independent from the original repository. If the original repository is deleted, the fork remains. If you fork a repository, you get that repository and all of its branches.

**What is the benefit of having a copy of the last known state of the remote
stored locally?**
You have posibillity add changes to this repository.

**How would you collaborate without using Git or GitHub?  What would be easier,
and what would be harder?**
I'll use Google docs, however I hope I won't need it.

**When would you want to make changes in a separate branch rather than directly in
master?  What benefits does each approach have?**
As for me, it's better do all changes in a separative branch, and after test it merge with master branch. It takes us to avoid errors in general.
