### ISSUE TITLE
Learn Git Branching in Browser

### ISSUE THREAD

**Issue by bazzika** [nesterone/sf-eng-init-gl-spring-2016#94]
https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/00-bootcamp/05-git-and-github/git-and-github.md#workshop-learn-git-branching-in-browser

**Comment by nesterone** [comment]
profs please

**Comment by bazzika** [comment]
abandoned

**Comment by bazzika** [comment]
[!image](http://screencast.com/t/cI7JpByg89)

**Comment by bazzika** [comment]
![image1](https://cloud.githubusercontent.com/assets/12714598/14210948/05cc9070-f834-11e5-86eb-ceb87eca9e68.png)
![im2](https://cloud.githubusercontent.com/assets/12714598/14210971/312d69c4-f834-11e5-8074-9aa28b85dfe9.png)
